var quotes = [
	"Always have faith. Always have hope",
	"The key is to make it",
	"Another one",
	"The key to more success is a clean heart and clean face",
	"You smart. You loyal. You're a genius",
	"They get mad when you have joy",
	"We're going to win",
	"They will try to close the door on you. Just open it",
	"They don't want you to win",
	"Those that weather the storm are the great ones",
	"You need to remember",
	"There will be road blocks, but we will overcome it",
	"They don't want you to jet ski",
	"Congratulations, you played yourself",
	"You want my advice? Don't play yourself",
	"I can deal with everything. I got the answer for anything",
	"The key is to have more water",
	"Celebrate success right",
	"Never give up",
	"Boomin'",
	"Major key, bless up",
	"Let's win more",
	"Life is what you make it, so make it.",
	"Make life amazing",
	"Some days the sun will be out, and some days it won't",
	"The key is to give thanks for everyday",
	"We the best",
	"Walk with me through the pathway to more success",
	"Enjoy life, live it up",
	"They don't want you to smile, so smile",
	"Mogul talk, win more",
	"Lion!",
	"They don't want you to eat right",
	"The key is to win more",
	"Surround yourself with angels, always",
	"Bless up",
	"Another one",
	"Major key",
	"Be great",
	"God gave us all this greatness to grow. Grow, but grow great",
	"We will overcome it",
	"You will experience road blocks. Overcome it",
	"Give thanks",
	"The key is to make it through any situation",
	"We have to work hard, we have no choice",
	"Never give up",
	"Stay away from they",
	"Never give up. Never surrender"
];